#!/bin/sh
# Regenerates core/tls_roots.c from third_party/roots/*.pem.
# Needs the host brssl tool: make -C third_party/bearssl
set -e
cd "$(dirname "$0")/.."
BRSSL=third_party/bearssl/build/brssl
[ -x "$BRSSL" ] || make -C third_party/bearssl -j4 >/dev/null
{
  echo '/* Generated by tools/gen_roots.sh from third_party/roots/ (brssl ta). Do not edit. */'
  echo '#include "tls_roots.h"'
  echo
  "$BRSSL" ta third_party/roots/*.pem 2>/dev/null
  echo
  echo 'const br_x509_trust_anchor *vjo_tls_roots = TAs;'
  echo 'const size_t vjo_tls_roots_num = TAs_NUM;'
} > core/tls_roots.c
echo "wrote core/tls_roots.c"
